### ISSUE TITLE
crash when writing first char to a new file

### ISSUE THREAD

**Issue by xobyx** [appt2/Ghost-web-ide#24]
Telephony Information:
- Sim Operator Name: du
- Phone Type: GSM
SDK: 29
Android: 10
Model: A600FJXU9CVB1
App version: 1.5.6

java.lang.NullPointerException: Attempt to invoke interface method 'int java.lang.CharSequence.length()' on a null object reference
	at android.text.SpannableString.<init>(SpannableString.java:34)
	at android.text.SpannableString.<init>(SpannableString.java:43)
	at android.text.Spannable$Factory.newSpannable(Spannable.java:82)
	at io.github.rosemoe.sora.widget.CustomAdGhostWeb.getView(CustomAdGhostWeb.java:60)
	at io.github.rosemoe.sora.widget.EditorCompletionAdapter.getView(EditorCompletionAdapter.java:61)
	at android.widget.AbsListView.obtainView(AbsListView.java:3271)
	at android.widget.ListView.makeAndAddView(ListView.java:2238)
	at android.widget.ListView.fillDown(ListView.java:838)
	at android.widget.ListView.fillFromTop(ListView.java:900)
	at android.widget.ListView.layoutChildren(ListView.java:1974)
	at android.widget.AbsListView.onLayout(AbsListView.java:3041)
	at android.view.View.layout(View.java:23754)
	at android.view.ViewGroup.layout(ViewGroup.java:7277)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1818)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1584)
	at android.view.View.layout(View.java:23754)
	at android.view.ViewGroup.layout(ViewGroup.java:7277)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23754)
	at android.view.ViewGroup.layout(ViewGroup.java:7277)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1213)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:899)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:919)
	at android.view.View.layout(View.java:23754)
	at android.view.ViewGroup.layout(ViewGroup.java:7277)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:23754)
	at android.view.ViewGroup.layout(ViewGroup.java:7277)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3680)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3140)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2201)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9000)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:996)
	at android.view.Choreographer.doCallbacks(Choreographer.java:794)
	at android.view.Choreographer.doFrame(Choreographer.java:729)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:981)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:7948)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)

Thu Feb 29 01:26:37 GMT+04:00 2024

**Comment by appt2** [comment]
@xobyx you have folder `/storage/emulated/0/GhostWebIDE/codeHelper` ?

**Comment by appt2** [comment]
If you use a certain language, json may be damaged. Go to the mentioned folder and put a [] inside the json auxiliary language file.

**Comment by xobyx** [comment]
> @xobyx you have folder `/storage/emulated/0/GhostWebIDE/codeHelper` ?

yes 

> If you use a certain language, json may be damaged. Go to the mentioned folder and put a [] inside the json auxiliary language file.
lang.python.json Contains:
[
    {
        "name": "ninja",
        "value": "Test code",
        "sp": "make test code"
    }
]

**Comment by appt2** [comment]
> > @xobyx you have folder `/storage/emulated/0/GhostWebIDE/codeHelper` ?
> 
> yes
> 
> > If you use a certain language, json may be damaged. Go to the mentioned folder and put a [] inside the json auxiliary language file.
> > lang.python.json Contains:
> > [
> > {
> > "name": "ninja",
> > "value": "Test code",
> > "sp": "make test code"
> > }
> > ]

using [] and test

**Comment by appt2** [comment]
I understand your problem, if you don't want to use the auxiliary code option, just put a [], if not, your Json must contain 2 elements, as if a single element is not accepted.

```json

[
  {
    "name": "myapp",
    "value": "pass",
    "sp": "mypass"
  },
  {
    "name": "pa33",
    "value": "pass33",
    "sp": "oeoe"
  }
]
```

**Comment by xobyx** [comment]
> using [] and test

It works! Thanks
